# Generated by Django 4.2 on 2023-04-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Course_details',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='course',
            new_name='course_id',
        ),
    ]
