# Generated by Django 4.1.7 on 2023-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
